version: '3.9'

services:
  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-postgres} -d ${POSTGRES_DB:-task_manager_db}"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  web:
    build: .
    command: sh -c "alembic upgrade head && uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload"
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    env_file:
      - .env
    environment:
      - DB_HOST=db
      - REDIS_URL=redis://redis:6379/0

  celery_worker:
    build: .
    command: celery -A app.core.celery worker --pool=solo -l INFO
    #command: celery -A app.core.celery worker -P asyncio -l INFO
    #Проблема выше с использованием event loop (SQlAlchemy путает loop с Celery)
    #Пока вся логика в Celery синхронная, потом возможно переделать!
    volumes:
      - .:/app
    depends_on:
      - redis
      - db
    env_file:
      - .env
    environment:
      - REDIS_URL=redis://redis:6379/0
      - DB_HOST=db

  celery_beat:
    build: .
    command: celery -A app.core.celery beat -l INFO
    volumes:
      - .:/app
    depends_on:
      - redis
      - celery_worker
    env_file:
      - .env
    environment:
      - REDIS_URL=redis://redis:6379/0

volumes:
  postgres_data:
  redis_data:
