"""Add assignee to tasks

Revision ID: 15d999225fb1
Revises: 19e99c269a2c
Create Date: 2026-07-28 04:41:41.224191

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '15d999225fb1'
down_revision: Union[str, None] = '19e99c269a2c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('assignee_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'tasks', 'users', ['assignee_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.drop_column('tasks', 'assignee_id')
    # ### end Alembic commands ###
