"""Add notification tracking fields

Revision ID: ebf3d20dec74
Revises: 976855c0d052
Create Date: 2026-08-20 14:20:32.038867

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ebf3d20dec74'
down_revision: Union[str, None] = '976855c0d052'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('cancelled_by_inactivity', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'cancelled_by_inactivity')
    # ### end Alembic commands ###
